site_name: Grupo 4 ArqDSW
repo_url: https://github.com/UnBArqDsw2021-2/2021.2_G4_ProjetoProdutores_docs

theme:
  name: material
  features: navigation.tabs

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Base:
    - Iniciativas Extras:
      - Ata de Reunião 24/01: reunioes/ata_24_01.md
    - Módulo Projeto Não Orientado a Abordagens Específicas:
      - Requisitos:
        - Pré-Rastreabilidade:
          - Mapa Mental: requisitos/preRastreabilidade/mapasMentais.md
  # - Modelagem: ""
  # - Padrões de Projeto: ""
  # - Arquitetura de Software e Reutilização: ""