site_name: Caderneta de Campo Digital
repo_url: https://github.com/UnBArqDsw2021-2/2021.2_G4_ProjetoProdutores_docs

theme:
  name: material
  features: navigation.tabs
  logo: assets/logo_branca.png
  favicon: assets/logo_branca.png

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Base:            
    - Processos, Metodologias e Abordagens:
      - Metodologia: base/metodologia.md
      - Modelagem BPMN: base/modelagem_bpmn.md
    - Módulo Projeto Não Orientado a Abordagens Específicas:
      - Design Sprint: base/design_sprint.md
      - Requisitos:
        - Pré-Rastreabilidade:
          - Rich Picture: base/requisitos/preRastreabilidade/rich_picture.md
          - Mapa Mental: requisitos/pre_rastreabilidade/mapas_mentais.md
          - 5W2H: base/5W2H.md
        - Elicitação:
          - Brainstorming: requisitos/elicitacao/brainstorming.md
          - Causa e Efeito: requisitos/elicitacao/diagrama_causa_efeito.md
          - Entrevista: requisitos/elicitacao/entrevista.md
          - Introspecção: requisitos/elicitacao/introspeccao.md
          - Personas: requisitos/elicitacao/personas.md
          - Storytelling: requisitos/elicitacao/storytelling.md
        - Priorização:
          - First Thing First: requisitos/priorizacao/first_things_first.md
          - Moscow: requisitos/priorizacao/moscow.md
        - Modelagem:
          - Léxicos: requisitos/modelagem/lexicos.md
      - Prototipação: 
        - Introdução: base/prototipacao/introducao.md
        - Protótipo de Baixa Fidelidade: base/prototipacao/baixa_fidelidade.md
        - Protótipo de Média Fidelidade: base/prototipacao/media_fidelidade.md
    - Iniciativas Extras:      
      - Termo de Abertura de Projeto: base/termo_de_abertura.md
      - Atas:
        - Ata de Reunião 24/01: reunioes/ata_24_01.md
        - Ata de Reunião 25/01: reunioes/ata_25_01.md
        - Ata de Reunião 31/01: reunioes/ata_31_01.md
      - Política de Contribuição: base/politicas_de_contribuicao.md
      - Manual de Identidade Visual: base/manual_identidade_visual.md
    - Apresentações: apresentacoes/pc1.md
  - Modelagem:
    - Projeto Orientado a Abordagens Tradicionais:
      - Modelagem Estática:
      #   - Diagrama de Classe:
        - Diagrama de Pacotes: modelagem/estatica/diagrama_de_pacotes.md
        - Diagrama de Classes: modelagem/estatica/diagrama_de_classes.md
      #   - Diagrama de Pacotes:
        - Diagrama de Componentes: modelagem/estatica/diagrama_de_componentes.md
      # - Modelagem Dinâmica:
      #   - Diagrama de Sequência:
      #   - Diagrama de Comunicação:
      #   - Diagrama de Atividades:
      #   - Diagrama de Estados:
      - Modelagem Ágil:
      #   - Product Backlog:
        - Especificação Suplementar: modelagem/agil/especificacao_suplementar.md
      #   - NFR Framework:
    - Iniciativas Extras:      
      # - Modelagem Entidade-Relacionamento (MER):
      # - Diagrama Entidade-Relacionamento (DER):
      # - Diagrama Lógico de Dados (DLD):
      # - Dicionário de Dados:
      # - Casos de Uso:
      - Sprints:
        - Sprint 0:
          - Review: sprints/review_0.md
        - Sprint 1:
          - Planning: sprints/planning_1.md
      # - Atas:
  # - Padrões de Projeto: ""
  # - Arquitetura de Software e Reutilização: ""
