site_name: Grupo 4 ArqDSW
repo_url: https://github.com/UnBArqDsw2021-2/2021.2_G4_ProjetoProdutores

theme:
  name: material
  features: navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Base:
    - Processos, Metodologias e Abordagens:
      - Modelagem BPMN: base/modelagem_bpmn.md
      - Metodologia: base/metodologia.md
    - Iniciativas Extras:
      - Termo de Abertura de Projeto: base/termo_de_abertura.md
      - Ata de Reunião 24/01: reunioes/ata_24_01.md
  # - Modelagem: ""
  # - Padrões de Projeto: ""
  # - Arquitetura de Software e Reutilização: ""
