
  
site_name: Grupo 4 ArqDSW
repo_url: https://github.com/UnBArqDsw2021-2/2021.2_G4_ProjetoProdutores_docs

theme:
  name: material
  features: navigation.tabs

nav:
  - Home: index.md
  - Base:
    - Processos, Metodologias e Abordagens:
      - Metodologia: base/metodologia.md
      - Modelagem BPMN: base/modelagem_bpmn.md
    - Módulo Projeto Não Orientado a Abordagens Específicas:
      - Requisitos:
        - Pré-Rastreabilidade:
          - Rich Picture: base/requisitos/preRastreabilidade/rich_picture.md
        - Elicitação:
          - Brainstorming: requisitos/elicitacao/brainstorming.md
          - Entrevista: requisitos/elicitacao/entrevista.md
          - Introspecção: requisitos/elicitacao/introspeccao.md
    - Iniciativas Extras:
      - Atas:
        - Ata de Reunião 24/01: reunioes/ata_24_01.md
        - Ata de Reunião 25/01: reunioes/ata_25_01.md
      - Política de Contribuição: base/politicas_de_contribuicao.md
          
  # - Modelagem: ""
  # - Padrões de Projeto: ""
  # - Arquitetura de Software e Reutilização: ""
